{ pkgs }:
with pkgs.vimPlugins; [
  (nvim-treesitter.withPlugins (
    p: [
      p.javascript
      p.typescript
      p.json
      p.lua
      p.html
      p.bash
      p.css
      p.jsdoc
      p.nix
      p.scss
      p.tsx
      p.rust
    ]
  ))
  vim-fugitive
  auto-session
  nvim-web-devicons
  bufferline-nvim
  dracula-nvim
  catppuccin-nvim
  tokyonight-nvim
  nvim-cmp
  cmp-nvim-lsp
  cmp-buffer
  cmp-path
  cmp-cmdline
  cmp-nvim-ultisnips
  cmp-emoji
  cmp_luasnip
  luasnip
  indent-blankline-nvim
  which-key-nvim
  neo-tree-nvim
  plenary-nvim
  nui-nvim
  no-neck-pain-nvim
  rust-tools-nvim
  comment-nvim
  lualine-nvim
  lsp-status-nvim
  telescope-nvim
  rose-pine
  bufdelete-nvim
  harpoon
  nvim-lspconfig
  telescope-recent-files
]
